### ISSUE TITLE
Port Tunernome

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#31]
- [x] Color
- [ ] More color?
- [ ] Fix swing arc to be middle 90 degrees?
- [ ] https://github.com/AEFeinstein/Super-2023-Swadge-FW/issues/31#issuecomment-1282288832 ?
- [x] Buzzer integration
- [x] Resize everything for the larger screen (no more tiny font)
- [x] Split tuner and metronome arm lengths, lengthen metronome
- [x] Update UI for D-Pad, A, B, Start, Select
- [x] Add text to "Listening" tuner setting to make it more obvious what's going on
- [x] Fix up arrow and flat symbol pngs not working
- [x] Fix exit functionality
- [x] Fix metronome BPM button timers being fucky
- [x] Fix non-deterministic horizontal spacing of sharp/flat notes displayed (is this magically fixed after the latest master merge?)
- [x] Fix mic occasionally not working (untested on HW) (is this still an issue? marking it done unless I reproduce it)
- [x] Fix LED positions
- [ ] Fix time signatures only really taking top number into account
- [ ] Fix time signatures to differentiate between note values
- [ ] Improve note value differentiation for light flashes
- [ ] Improve note value differentiation for buzzer beeps
- [ ] Improve downbeat differentiation for light flashes
- [ ] Improve downbeat differentiation for buzzer beeps

**Comment by Brycey92** [comment]
This is a non-exhaustive list of changes I've found to be needed when porting Tunernome. They should vastly cut down on time required to port something, since much of that time involves relearning where everything went.

# Things to add to tunernomeEnterMode
tunernome-> disp = disp;

loadFont("tom_thumb.font", &tunernome->tom_thumb);
loadFont("ibm_vga8.font", &tunernome->ibm_vga8);
loadFont("radiostars.font", &tunernome->radiostars);

# Things to add to tunernomeExitMode
freeFont(&tunernome->tom_thumb);
freeFont(&tunernome->ibm_vga8);
freeFont(&tunernome->radiostars);

# Functions that need to be intelligently changed or replaced
tunernomeButtonCallback(uint8_t state, int button, int down)
tunernomeButtonCallback(buttonEvt_t* evt)

plotText(xOff, yOff, text, font, color)
drawText(disp, font, color, text, xOff, yOff)

textWidth(string, font)
textWidth(font, string)

plotText(xOff, yOff, string, font, color)
drawText(disp, font, color, string, xOff, yOff)

# Things that can be find/replaced
clearDisplay
tunernome->disp->clearPx

drawPixel
tunernome->disp->setPx

os_malloc
malloc

os_free
free

ets_memset
memset

ets_strlen
strlen

ets_snprintf
snprintf

system_get_time
esp_timer_get_time

IBM_VGA_8
&tunernome->ibm_vga8

TOM_THUMB
&tunernome->tom_thumb

FONT_HEIGHT_IBMVGA8
tunernome->ibm_vga8.h

FONT_HEIGHT_TOMTHUMB
tunernome->tom_thumb.h

EnterMode(void)
EnterMode(display_t * disp)

RenderTask(void)
MainLoop(int64_t elapsedUs)

ICACHE_FLASH_ATTR


NUM_LIN_LEDS
NUM_LEDS

OLED_WIDTH
tunernome->disp->w

OLED_HEIGHT
tunernome->disp->h

ACTION
BTN_A

plotLine(
plotLine(tunernome->disp, 

WHITE
c555

BLACK
c000

TRANSPARENT_COLOR
cTransparent

pngHandle
wsg_t

loadPngAsset
loadWsg

freePngAsset
freeWsg

drawPng
drawWsg

**Comment by AEFeinstein** [comment]
@Brycey92 is there anything you _need_ to do besides update the metronome arm length and adjust the LEDs so that the correct positions are shining? Seems like you did the color and UI bits, though maybe you had more in mind?

**Comment by AEFeinstein** [comment]
I guess you could rework it to not have 'left' be the exit button, since 'start + select' does that.

**Comment by Brycey92** [comment]
I could adjust the metronome arm length, if I split it from the tuner arm length. Adjusting LEDs is on the to-do list potentially tonight.

I had some ideas to rework some button controls, but I'm coming up flat for visual design rework. Will probably not have time for UI visual redesign myself, since Dac and I have plans for me to write up to 2 more modes (Swadgestrument which will be kinda like the Kirby swadge but with less buttons and "instruments", and a Jukebox mode which will play all the bgms on the swadge)

**Comment by AEFeinstein** [comment]
Ah, I didn't realize the arm lengths were linked. Split 'em!

I'd strongly recommend you finish up this and #127 before embarking on Swadgestrument or Jukebox.

**Comment by Brycey92** [comment]
Ellie's splittin' em, and fixing some of the other to-dos on here, as I teach her how to program in C and for swadges

**Comment by AEFeinstein** [comment]
Good deal. @arty01238 I had an idea. `fourNoteStringIdxToLedIdx` was a way to show four things on six LEDs, but we have either LEDs now. That's nicely divisible! Just put each note on two adjacent LEDs!

**Comment by AEFeinstein** [comment]
This ticket has two branches with unmerged changes, [`tunernome`](https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tunernome) and [`tunernome-new-math`](https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tunernome-new-math). @Brycey92 and @haloflooder, make sure to iron this out and get a PR in before the 6th!

**Comment by Brycey92** [comment]
[`OBSOLETE_tunernome-new-math`](https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/OBSOLETE_tunernome-new-math) is obsolete, the only branch we need to worry about is [`tunernome`](https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tunernome). Still need @haloflooder's input on whether his changes are done.
