### ISSUE TITLE
Fullscreen Arg

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#348]
After https://github.com/cntools/rawdraw/pull/93 is accepted, update this project's `rawdraw_sf.h` and add a command line arg to either call either `CNFGSetup()` (what is currently done) or `CNFGSetupFullscreen()`

**Comment by AEFeinstein** [comment]
@dylwhich the branch is ready for arg-ifying

**Comment by dylwhich** [comment]
@AEFeinstein Okay, I added the command-line arg but I can't tell if it works. I'm using Wayland and all `--fullscreen` does is make the emu screen a bit smaller for some reason.

I also added a check to exit if `CNFGHandleInput()` returns 0 since it no longer does `exit(0)` itself. I noticed that one of the implementations of still returns a void so that may need to be fixed upstream.

**Comment by AEFeinstein** [comment]
rawdraw: it's production ready! I'll test it on Windows tonight.
Feel free to propose upstream changes to rawdraw directly:
https://github.com/cntools/rawdraw

**Comment by dylwhich** [comment]
Ah, okay upon examining further in the separate files, that's just the signature it gets if `CNFGRASTERIZER` isn't defined, but it matches up either way so I think that's fine.

**Comment by dylwhich** [comment]
So in order for fullscreen to work on linux, we just needed `HAS_XINERAMA=1` and to link against `Xext` and `Xinerama`, both of which were already needed to build (and included in the readme), but only for the headers I guess. I also added `FULL_SCREEN_STEAL_FOCUS=1` which also only applies to Linux.

**Comment by AEFeinstein** [comment]
Done in #356
