### ISSUE TITLE
Airplane mode

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#377]
We have toggles for audio, so why not have an airplane-mode toggle for next year? How hard could it be to implement? [Famous last words]

**Comment by AEFeinstein** [comment]
Probably not colossally difficult, but also far less useful than the audio toggle. There's no transmission unless you're doing something explicitly wireless anyway

**Comment by Brycey92** [comment]
True, but our audio mute also stops the user from accidentally doing things that use audio. Figured that would be the most useful effect of an airplane mode; to stop a user from accidentally doing things that transmit when airplane mode is on

**Comment by AEFeinstein** [comment]
But nobody cares! Audio is important because others around you can hear it. [Wi-fi allergies are not real](https://en.wikipedia.org/wiki/Electromagnetic_hypersensitivity). What is the tangible benefit for a Swadge user?

It also incurs extra work on modes where wireless is used. If audio is off, fine, no big deal. If wireless is off, silent failures are really bad. We'd have to have jukebox-style labels or something for all those cases.

**Comment by Brycey92** [comment]
I'm pretty sure airplane mode [doesn't exist for Wi-fi allergies](https://en.wikipedia.org/wiki/Mobile_phones_on_aircraft). Tangible benefit is small: the ability to use a Swadge on an airplane without being able to accidentally do something that transmits.

Though since you're right about it incurring extra work on every mode that uses wireless, perhaps the tangible benefit is too small for the extra cost in dev/testing labor. Shall we close this?

**Comment by AEFeinstein** [comment]
> Contrary to popular misconception, the [Federal Aviation Administration](https://en.wikipedia.org/wiki/Federal_Aviation_Administration) (FAA) does not actually prohibit the use of personal electronic devices (including cell phones) on aircraft.

The benefit doesn't outweigh the cost. Close it out.
